### ISSUE TITLE
Text overflow is happening when you refresh the page.

### ISSUE THREAD

**Issue by ps-raghotham-rao** [WebDevSHORTS/Parallax-Star-Background#1]
There is text overflow when you refresh the page.
![image](https://user-images.githubusercontent.com/73742827/102859892-d23aad80-4452-11eb-9f93-f993fb7116b2.png)

**Comment by ps-raghotham-rao** [comment]
div {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  
  You can use the above lines and it solves the problem.

**Comment by Masayidalfa** [comment]
great thank u
